=== myclabs/Units/src/MyCLabs/UnitBundle/Resources/data/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/extension"
        xmlns:tns="http://www.example.org/extension"
        elementFormDefault="qualified">


    <element name="xml">
        <complexType>
            <sequence>
                <element name="extension" type="tns:extension" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="extension">
        <sequence>
            <element name="name" type="tns:name"/>
            <element name="symbol" type="tns:name"/>
            <element name="multiplier" type="float"/>
        </sequence>
        <attribute name="ref" type="tns:refType" use="required"/>
    </complexType>

    <simpleType name="refType">
        <restriction base="string">
            <pattern value="([a-z0-9_-])*"/>
        </restriction>
    </simpleType>

    <complexType name="name">
        <sequence>
            <element name="fr" type="string"/>
            <element name="en" type="string"/>
        </sequence>
    </complexType>
</schema>

=== myclabs/Units/src/MyCLabs/UnitBundle/Resources/data/extension.xml
<?xml version="1.0" encoding="UTF-8"?>

<xml xmlns="http://www.example.org/extension"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.example.org/extension extension.xsd ">

    <!-- Pour toutes les conventions relatives à l'ordre entre les objets, le choix des identifiants, des symboles, et des libellés, voir specs -->

    <extension ref="co2e">
        <name>
            <fr>équivalent CO2</fr>
            <en>CO2 equivalent</en>
        </name>
        <symbol>
            <fr>équ. CO2</fr>
            <en>CO2 eq.</en>
        </symbol>
        <multiplier>1</multiplier>
    </extension>

    <extension ref="ce">
        <name>
            <fr>équivalent carbone</fr>
            <en>carbon equivalent</en>
        </name>
        <symbol>
            <fr>équ. C</fr>
            <en>C eq.</en>
        </symbol>
        <multiplier>3.666666667</multiplier>
    </extension>

</xml>
