=== myclabs/Units/src/MyCLabs/UnitBundle/Resources/data/quantities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/quantities"
        xmlns:tns="http://www.example.org/quantities"
        elementFormDefault="qualified">

    <element name="xml">
        <complexType>
            <sequence>
                <element name="quantity" type="tns:quantity" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="quantity">
        <sequence>
            <element name="name" type="tns:name"/>
            <element name="standardUnitRef" type="string"/>
            <element name="symbol" type="string"/>
            <element name="isBase" type="boolean"/>
            <element name="component" type="tns:component" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="ref" type="tns:refType" use="required"/>
    </complexType>

    <complexType name="component">
        <sequence>
            <element name="baseQuantityRef" type="string"/>
            <element name="exponent" type="integer"/>
        </sequence>
    </complexType>

    <simpleType name="refType">
        <restriction base="string">
            <pattern value="([a-z0-9_-_/])*"/>
        </restriction>
    </simpleType>

    <complexType name="name">
        <sequence>
            <element name="fr" type="string"/>
            <element name="en" type="string"/>
        </sequence>
    </complexType>

</schema>

=== myclabs/Units/src/MyCLabs/UnitBundle/Resources/data/quantities.xml
<?xml version="1.0" encoding="UTF-8"?>

<xml xmlns="http://www.example.org/quantities"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.example.org/quantities quantities.xsd ">

    <!-- Pour toutes les conventions relatives à l'ordre entre les objets, le choix des identifiants, des symboles, et des libellés, voir specs -->

    <!--  Exposant zéro -->

    <quantity ref="sans_dimension">
        <name>
            <fr>Sans dimension</fr>
            <en>Without dimension</en>
        </name>
        <standardUnitRef>un</standardUnitRef>
        <symbol/>
        <isBase>false</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>

    <!-- Exposant 1 -->

    <quantity ref="l">
        <name>
            <fr>Longueur</fr>
            <en>Length</en>
        </name>
        <standardUnitRef>m</standardUnitRef>
        <symbol>L</symbol>
        <isBase>true</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>1</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>

    <quantity ref="m">
        <name>
            <fr>Masse</fr>
            <en>Mass</en>
        </name>
        <standardUnitRef>kg</standardUnitRef>
        <symbol>M</symbol>
        <isBase>true</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>1</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>

    <quantity ref="t">
        <name>
            <fr>Temps</fr>
            <en>Time</en>
        </name>
        <standardUnitRef>s</standardUnitRef>
        <symbol>T</symbol>
        <isBase>true</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>1</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>

    <quantity ref="numeraire">
        <name>
            <fr>Numéraire</fr>
            <en>Numerical</en>
        </name>
        <standardUnitRef>euro</standardUnitRef>
        <symbol>Num</symbol>
        <isBase>true</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>1</exponent>
        </component>
    </quantity>

    <!-- Exposant 2 -->

    <quantity ref="l2">
        <name>
            <fr>Surface</fr>
            <en>Area</en>
        </name>
        <standardUnitRef>m2</standardUnitRef>
        <symbol>L2</symbol>
        <isBase>false</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>2</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>

    <quantity ref="l/t">
        <name>
            <fr>Vitesse</fr>
            <en>Speed</en>
        </name>
        <standardUnitRef>m/s</standardUnitRef>
        <symbol>L/T</symbol>
        <isBase>false</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>1</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>-1</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>

    <!-- Exposant 3 -->

    <quantity ref="l3">
        <name>
            <fr>Volume</fr>
            <en>Volume</en>
        </name>
        <standardUnitRef>m3</standardUnitRef>
        <symbol>L3</symbol>
        <isBase>false</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>3</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>0</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>

    <!-- Exposant 4 -->

    <!-- Exposant 5 -->

    <quantity ref="ml2/t2">
        <name>
            <fr>Énergie</fr>
            <en>Energy</en>
        </name>
        <standardUnitRef>j</standardUnitRef>
        <symbol>ML2/T2</symbol>
        <isBase>false</isBase>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>2</exponent>
        </component>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>1</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>-2</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>

    <!-- Exposant 6 -->

    <quantity ref="ml2/t3">
        <name>
            <fr>Puissance</fr>
            <en>Power</en>
        </name>
        <standardUnitRef>w</standardUnitRef>
        <symbol>ML2/T3</symbol>
        <isBase>false</isBase>
        <component>
            <baseQuantityRef>m</baseQuantityRef>
            <exponent>1</exponent>
        </component>
        <component>
            <baseQuantityRef>l</baseQuantityRef>
            <exponent>2</exponent>
        </component>
        <component>
            <baseQuantityRef>t</baseQuantityRef>
            <exponent>-3</exponent>
        </component>
        <component>
            <baseQuantityRef>numeraire</baseQuantityRef>
            <exponent>0</exponent>
        </component>
    </quantity>


</xml>
