=== myclabs/Units/src/MyCLabs/UnitBundle/Resources/data/unitSystem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/unitSystem"
        xmlns:tns="http://www.example.org/unitSystem"
        elementFormDefault="qualified">

    <element name="xml">
        <complexType>
            <sequence>
                <element name="unitSystem" type="tns:unitSystem" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="unitSystem">
        <sequence>
            <element name="name" type="tns:name"/>
        </sequence>
        <attribute name="ref" type="tns:refType" use="required"/>
    </complexType>

    <simpleType name="refType">
        <restriction base="string">
            <pattern value="([a-z0-9_-])*"/>
        </restriction>
    </simpleType>

    <complexType name="name">
        <sequence>
            <element name="fr" type="string"/>
            <element name="en" type="string"/>
        </sequence>
    </complexType>
</schema>

=== myclabs/Units/src/MyCLabs/UnitBundle/Resources/data/unitSystem.xml
<?xml version="1.0" encoding="UTF-8"?>

<xml xmlns="http://www.example.org/unitSystem"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.example.org/unitSystem unitSystem.xsd ">

    <!-- Pour toutes les conventions relatives à l'ordre entre les objets, le choix des identifiants, des symboles, et des libellés, voir specs -->

    <unitSystem ref="international">
        <name>
            <fr>International</fr>
            <en>International</en>
        </name>
    </unitSystem>

    <unitSystem ref="anglo_saxon">
        <name>
            <fr>Anglo-saxon</fr>
            <en>Anglo-saxon</en>
        </name>
    </unitSystem>

</xml>
